"""add expense table

Revision ID: 0067294c7429
Revises: 3f8fd37f8997
Create Date: 2026-08-17 20:06:40.784318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0067294c7429'
down_revision: Union[str, Sequence[str], None] = '3f8fd37f8997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ENUM existente
payment_method = postgresql.ENUM(
    "EFECTIVO",
    "TRANSFERENCIA",
    name="paymentmethod",
    create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
                    sa.Column('expense_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('method', payment_method, nullable=False),
                    sa.Column('expense_type', sa.Enum('COMPRAS', 'GASOLINA',
                                                      'SERVICIO', 'OTRO', name='expensetype'), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(
                        length=200), nullable=True),
                    sa.Column('movement_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['movement_id'], ['cashmovement.movement_id'], ),
                    sa.PrimaryKeyConstraint('expense_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    # ### end Alembic commands ###
