"""adding differebce column on cash

Revision ID: 054750e46ec4
Revises: 9e01ad4ee944
Create Date: 2026-08-17 21:56:48.257031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054750e46ec4'
down_revision: Union[str, Sequence[str], None] = '9e01ad4ee944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashsession', sa.Column('expec_closing_balance', sa.Integer(), nullable=True))
    op.add_column('cashsession', sa.Column('difference', sa.Integer(), nullable=True))
    op.alter_column('cashsession', 'closing_balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cashsession', 'closing_balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('cashsession', 'difference')
    op.drop_column('cashsession', 'expec_closing_balance')
    # ### end Alembic commands ###
