"""adding user table

Revision ID: 28f22c5f1f6a
Revises: 4eb16e1869e2
Create Date: 2026-08-27 10:44:31.162170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28f22c5f1f6a'
down_revision: Union[str, Sequence[str], None] = '4eb16e1869e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=False),
                    sa.Column('password_hash',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('role', sa.Enum('ADMIN', 'MESERO',
                                              'CLIENTE', name='userrole'), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('user_id'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
