"""add cashsession and cashmovement tables

Revision ID: 3f8fd37f8997
Revises: 87e437573e60
Create Date: 2026-08-16 21:37:37.396192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3f8fd37f8997'
down_revision: Union[str, Sequence[str], None] = '87e437573e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ENUM existente
payment_method = postgresql.ENUM(
    "EFECTIVO",
    "TRANSFERENCIA",
    name="paymentmethod",
    create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashsession',
                    sa.Column('cash_session_id', sa.Integer(), nullable=False),
                    sa.Column('opening_balance', sa.Integer(), nullable=False),
                    sa.Column('closing_balance', sa.Integer(), nullable=True),
                    sa.Column('opened_at', sa.DateTime(), nullable=True),
                    sa.Column('closed_at', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.Enum('ABIERTA', 'CERRADA',
                                                name='cashstatus'), nullable=False),
                    sa.PrimaryKeyConstraint('cash_session_id')
                    )
    op.create_table('cashmovement',
                    sa.Column('movement_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('payment_method',
                              payment_method, nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('movement_type', sa.Enum(
                        'INGRESO', 'GASTO', name='movementtype'), nullable=True),
                    sa.Column('cash_session_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['cash_session_id'], [
                        'cashsession.cash_session_id'], ),
                    sa.PrimaryKeyConstraint('movement_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashmovement')
    op.drop_table('cashsession')
    # ### end Alembic commands ###
