"""removing column movement_id on payment

Revision ID: 4eb16e1869e2
Revises: 054750e46ec4
Create Date: 2026-08-19 16:29:09.345727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb16e1869e2'
down_revision: Union[str, Sequence[str], None] = '054750e46ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payment_movement_id_key'), 'payment', type_='unique')
    op.drop_constraint(op.f('payment_movement_id_fkey'), 'payment', type_='foreignkey')
    op.drop_column('payment', 'movement_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('movement_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('payment_movement_id_fkey'), 'payment', 'cashmovement', ['movement_id'], ['movement_id'])
    op.create_unique_constraint(op.f('payment_movement_id_key'), 'payment', ['movement_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
