"""first revision

Revision ID: 81d2cdbec529
Revises: 
Create Date: 2026-07-24 15:57:14.338792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81d2cdbec529'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.Column('document', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=False),
                    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=True),
                    sa.Column('cellphone', sqlmodel.sql.sqltypes.AutoString(
                        length=20), nullable=True),
                    sa.Column(
                        'address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('customer_id')
                    )
    op.create_index(op.f('ix_customer_document'),
                    'customer', ['document'], unique=True)
    op.create_table('menu',
                    sa.Column('menu_id', sa.Integer(), nullable=False),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(
                        length=20), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(
                        length=150), nullable=True),
                    sa.PrimaryKeyConstraint('menu_id')
                    )
    op.create_table('menuitem',
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Boolean(), nullable=False),
                    sa.Column('quant', sa.Integer(), nullable=True),
                    sa.Column('menu_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['menu_id'], ['menu.menu_id'], ),
                    sa.PrimaryKeyConstraint('item_id')
                    )
    op.create_table('order',
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.Column('total', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('order_type', sa.Enum('LOCAL', 'TAKEAWAY',
                                                    'DELIVERY', name='ordertype'), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'READY', 'DELIVERED',
                                                'PAID', 'CANCELLED', name='orderstatus'), nullable=False),
                    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(
                        length=20), nullable=True),
                    sa.Column('cellphone', sqlmodel.sql.sqltypes.AutoString(
                        length=12), nullable=True),
                    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['customer_id'], ['customer.customer_id'], ),
                    sa.PrimaryKeyConstraint('order_id')
                    )
    op.create_table('orderitem',
                    sa.Column('order_item_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('quant', sa.Integer(), nullable=False),
                    sa.Column('unit_price', sa.Integer(), nullable=True),
                    sa.Column('total_item', sa.Integer(), nullable=True),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['item_id'], ['menuitem.item_id'], ),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['order.order_id'], ),
                    sa.PrimaryKeyConstraint('order_item_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitem')
    op.drop_table('order')
    op.drop_table('menuitem')
    op.drop_table('menu')
    op.drop_index(op.f('ix_customer_document'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
