"""adding 'created_at' on payment

Revision ID: 87e437573e60
Revises: 971de27d9868
Create Date: 2026-08-14 10:27:22.575066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e437573e60'
down_revision: Union[str, Sequence[str], None] = '971de27d9868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'created_at')
    # ### end Alembic commands ###
