"""setting movement_id unique

Revision ID: 9e01ad4ee944
Revises: b9feea1d2138
Create Date: 2026-08-17 20:19:31.885664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e01ad4ee944'
down_revision: Union[str, Sequence[str], None] = 'b9feea1d2138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'expense', ['movement_id'])
    op.create_unique_constraint(None, 'payment', ['movement_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_constraint(None, 'expense', type_='unique')
    # ### end Alembic commands ###
