"""set product_name nullable on orderdetail

Revision ID: ae0b1d7ead0c
Revises: ce29ab129f78
Create Date: 2026-07-30 16:31:15.532987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0b1d7ead0c'
down_revision: Union[str, Sequence[str], None] = 'ce29ab129f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orderdetail', 'product_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'default_name'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orderdetail', 'product_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'default_name'::character varying"))
    # ### end Alembic commands ###
