"""add colum movement_id on payment

Revision ID: b9feea1d2138
Revises: 0067294c7429
Create Date: 2026-08-17 20:15:56.089863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9feea1d2138'
down_revision: Union[str, Sequence[str], None] = '0067294c7429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('movement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment', 'cashmovement', ['movement_id'], ['movement_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'movement_id')
    # ### end Alembic commands ###
