"""modifying order, customer, menu_item, renaming  order_item to order_detail

Revision ID: bc7b21c74a02
Revises: 81d2cdbec529
Create Date: 2026-07-28 11:22:24.270997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc7b21c74a02'
down_revision: Union[str, Sequence[str], None] = '81d2cdbec529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderdetail',
                    sa.Column('detail_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('unit_price', sa.Integer(), nullable=True),
                    sa.Column('subtotal', sa.Integer(), nullable=True),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['item_id'], ['menuitem.item_id'], ),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['order.order_id'], ),
                    sa.PrimaryKeyConstraint('detail_id')
                    )
    op.drop_table('orderitem')
    op.add_column('order', sa.Column(
        'phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('order', sa.Column('delivery_address',
                  sqlmodel.sql.sqltypes.AutoString(length=130), nullable=True))
    op.alter_column('order', 'customer_name',
                    existing_type=sa.VARCHAR(length=20),
                    type_=sqlmodel.sql.sqltypes.AutoString(length=50),
                    existing_nullable=True)
    op.drop_constraint(op.f('order_customer_id_fkey'),
                       'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'customer', ['customer_id'], [
                          'customer_id'], ondelete='CASCADE')
    op.drop_column('order', 'cellphone')
    op.drop_column('order', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('address', sa.VARCHAR(
        length=50), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('cellphone', sa.VARCHAR(
        length=12), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key(op.f('order_customer_id_fkey'), 'order', 'customer', [
                          'customer_id'], ['customer_id'])
    op.alter_column('order', 'customer_name',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
                    type_=sa.VARCHAR(length=20),
                    existing_nullable=True)
    op.drop_column('order', 'delivery_address')
    op.drop_column('order', 'phone')
    op.create_table('orderitem',
                    sa.Column('order_item_id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('quant', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('unit_price', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('total_item', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('item_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('order_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['item_id'], ['menuitem.item_id'], name=op.f('orderitem_item_id_fkey')),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['order.order_id'], name=op.f('orderitem_order_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'order_item_id', name=op.f('orderitem_pkey'))
                    )
    op.drop_table('orderdetail')
    # ### end Alembic commands ###
