"""product_name field added on order_detail table

Revision ID: ce29ab129f78
Revises: bc7b21c74a02
Create Date: 2026-07-30 10:24:36.831317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce29ab129f78'
down_revision: Union[str, Sequence[str], None] = 'bc7b21c74a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'orderdetail', sa.Column(
            'product_name',
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
            server_default='default_name'
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderdetail', 'product_name')
    # ### end Alembic commands ###
